bookstore/src/authentication/urls.py
from django.urls import path
from .views import *

app_name = 'profile'
urlpatterns = [
    path('signin/', AuthenticationView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', AuthLogoutView.as_view(), name='logout'),
    path('password_change/', AuthPasswordChangeView.as_view(), name='password-change'),
    path('password_change_success/', AuthPasswordUpdDoneView.as_view(), name='password-updt-success'),
    path('auth/', ProfileView.as_view(), name='profile-view'),
    path('<int:pk>/update/', UpdateProfileView.as_view(), name='profile-update'),
]

bookstore/src/manager_admin/urls.py
from django.urls import path
from .views import *

app_name = 'manager'
urlpatterns = [
    path('order/list/', ManagerOrderList.as_view(), name='order-list'),
    path('order/update/<int:pk>/', ManagerOrderUpdate.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', ManagerOrderDelete.as_view(), name='order-delete'),

    path('author/list/', AuthorList.as_view(), name='author-list'),
    path('author/create/', AuthorCreate.as_view(), name='author-create'),
    path('author/view/<int:pk>/', AuthorView.as_view(), name='author-view'),
    path('author/delete/<int:pk>/', AuthorDelete.as_view(), name='author-delete'),
    path('author/update/<int:pk>/', AuthorUpdate.as_view(), name='author-update'),


    path('series/list/', SeriesList.as_view(), name='series-list'),
    path('series/create/', SeriesCreate.as_view(), name='series-create'),
    path('series/view/<int:pk>/', SeriesView.as_view(), name='series-view'),
    path('series/update/<int:pk>/', SeriesUpdate.as_view(), name='series-update'),
    path('series/delete/<int:pk>/', SeriesDelete.as_view(), name='series-delete'),


    path('genre/list/', GenreList.as_view(), name='genre-list'),
    path('genre/create/', GenreCreate.as_view(), name='genre-create'),
    path('genre/view/<int:pk>/', GenreView.as_view(), name='genre-view'),
    path('genre/update/<int:pk>/', GenreUpdate.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>/', GenreDelete.as_view(), name='genre-delete'),


    path('publisher/list/', PublisherList.as_view(), name='publisher-list'),
    path('publisher/create/', PublisherCreate.as_view(), name='publisher-create'),
    path('publisher/view/<int:pk>/', PublisherView.as_view(), name='publisher-view'),
    path('publisher/update/<int:pk>/', PublisherUpdate.as_view(), name='publisher-update'),
    path('publisher/delete/<int:pk>/', PublisherDelete.as_view(), name='publisher-delete'),

    
    path('format/', FormatListView.as_view(), name = 'format-list-view'),
    path('format/<int:pk>/', FormatView.as_view(), name = 'format-view'),
    path('format/create/', CreateFormatView.as_view(), name = 'format-create'),
    path('format/update/<int:pk>/', UpdateFormatView.as_view(), name = 'format-update'),
    path('format/delete/<int:pk>/', DeleteFormatView.as_view(), name = 'format-delete'),
    
    path('age/', Age_resListView.as_view(), name = 'ageres-list-view'),
    path('age/<int:pk>/', Age_resView.as_view(), name = 'ageres-view'),
    path('age/create/', CreateAge_resView.as_view(), name = 'ageres-create'),
    path('age/update/<int:pk>/', UpdateAge_resView.as_view(), name = 'ageres-update'),
    path('age/delete/<int:pk>/', DeleteAge_resView.as_view(), name = 'ageres-delete'),
    
    path('rating/', RatingListView.as_view(), name = 'rating-list-view'),
    path('rating/<int:pk>/', RatingView.as_view(), name = 'rating-view'),
    path('rating/create/', CreateRatingView.as_view(), name = 'rating-create'),
    path('rating/update/<int:pk>/', UpdateRatingView.as_view(), name = 'rating-update'),
    path('rating/delete/<int:pk>/', DeleteRatingView.as_view(), name = 'rating-delete'),


    path('book/list/', ManagerBookList.as_view(), name='book-list'),
    path('book/create/', ManagerBookCreate.as_view(), name='book-create'),
    path('book/delete/<int:pk>/', ManagerBookDelete.as_view(), name='book-delete'),
    path('book/update/<int:pk>/', ManagerBookUpdate.as_view(), name='book-update'),
    path('book/view/<int:pk>/', ManagerBookView.as_view(), name='book-view'),


    path('customer/list/', CustomersList.as_view(), name='customer-list'),
    path('customer/update/<int:pk>/', CustomerUpdate.as_view(), name='customer-update'),
    path('customer/view/<int:pk>/', CustomerView.as_view(), name='customer-view')

    
]

bookstore/src/orders/urls.py
from django.urls import path
from django.views.generic.base import View

from book.views import *
from refference_db.views import *
from .views import *

app_name = 'orders'
urlpatterns = [
    path('', CartView.as_view(), name = 'cart'),
    path('update-cart', CartUpdateView.as_view(), name = 'update'),
    path('delete-book-in-cart/<int:pk>', DeleteBookInCart.as_view(), name = 'book-in-cart-del'),
    path('order/', CreateOrderView.as_view(), name='create-order'),
    path('history/', HistoryDetailView.as_view(), name='history')

]

bookstore/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from catalog.views import *
from book.views import *
from refference_db.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('authentication.urls', namespace='profile')),

    path('book/search/', BookSearch.as_view(), name='search'),
    path('book/<int:pk>/', BookView.as_view(), name = 'book-view'),
    path('book/create/', CreateBookView.as_view(), name = 'book-create'),
    path('book/update/<int:pk>/', UpdateBookView.as_view(), name = 'book-update'),
    path('book/delete/<int:pk>/', DeleteBookView.as_view(), name = 'book-delete'),

    path('genre/', GenreListView.as_view(), name = 'genre-list-view'),
    path('genre/<int:pk>/', GenreView.as_view(), name = 'genre-view'),
    path('genre/create/', CreateGenreView.as_view(), name = 'genre-create'),
    path('genre/update/<int:pk>/', UpdateGenreView.as_view(), name = 'genre-update'),
    path('genre/delete/<int:pk>/', DeleteGenreView.as_view(), name = 'genre-delete'),
    
    path('author/', AuthorListView.as_view(), name = 'author-list-view'),
    path('author/<int:pk>/', AuthorView.as_view(), name = 'author-view'),
    path('author/create/', CreateAuthorView.as_view(), name = 'author-create'),
    path('author/update/<int:pk>/', UpdateAuthorView.as_view(), name = 'author-update'),
    path('author/delete/<int:pk>/', DeleteAuthorView.as_view(), name = 'author-delete'),
    
    path('series/', SeriesListView.as_view(), name = 'series-list-view'),
    path('series/<int:pk>/', SeriesView.as_view(), name = 'series-view'),
    path('series/create/', CreateSeriesView.as_view(), name = 'series-create'),
    path('series/update/<int:pk>/', UpdateSeriesView.as_view(), name = 'series-update'),
    path('series/delete/<int:pk>/', DeleteSeriesView.as_view(), name = 'series-delete'),
    
    path('publisher/', PublisherListView.as_view(), name = 'publisher-list-view'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name = 'publisher-view'),
    path('publisher/create/', CreatePublisherView.as_view(), name = 'publisher-create'),
    path('publisher/update/<int:pk>/', UpdatePublisherView.as_view(), name = 'publisher-update'),
    path('publisher/delete/<int:pk>/', DeletePublisherView.as_view(), name = 'publisher-delete'),
    
    path('format/', FormatListView.as_view(), name = 'format-list-view'),
    path('format/<int:pk>/', FormatView.as_view(), name = 'format-view'),
    path('format/create/', CreateFormatView.as_view(), name = 'format-create'),
    path('format/update/<int:pk>/', UpdateFormatView.as_view(), name = 'format-update'),
    path('format/delete/<int:pk>/', DeleteFormatView.as_view(), name = 'format-delete'),
    
    path('age/', Age_resListView.as_view(), name = 'ageres-list-view'),
    path('age/<int:pk>/', Age_resView.as_view(), name = 'ageres-view'),
    path('age/create/', CreateAge_resView.as_view(), name = 'ageres-create'),
    path('age/update/<int:pk>/', UpdateAge_resView.as_view(), name = 'ageres-update'),
    path('age/delete/<int:pk>/', DeleteAge_resView.as_view(), name = 'ageres-delete'),
    
    path('rating/', RatingListView.as_view(), name = 'rating-list-view'),
    path('rating/<int:pk>/', RatingView.as_view(), name = 'rating-view'),
    path('rating/create/', CreateRatingView.as_view(), name = 'rating-create'),
    path('rating/update/<int:pk>/', UpdateRatingView.as_view(), name = 'rating-update'),
    path('rating/delete/<int:pk>/', DeleteRatingView.as_view(), name = 'rating-delete'),

    path('error/', ErrorView.as_view(), name = 'error'),
    path('empty/', EmptyView.as_view(), name = 'empty'),
    path('return/', ReturnView.as_view(), name = 'return'),
    path('about/', AboutView.as_view(), name = 'about'),
    path('shipping/', ShippingView.as_view(), name = 'shipping'),
    path('contacts/', ContactsView.as_view(), name = 'contacts'),
    path('cart/', include('orders.urls', namespace = 'orders')),
    path('catalog/', include('catalog.urls')),
    
    path('test/', BookListView.as_view(), name = 'main-manager'),
    path('manager/', include('manager_admin.urls', namespace = 'manager')),
    path('', MainPageView.as_view(), name = 'main')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/src/book/models.py
from django.db import models
from refference_db.models import *
from datetime import date

class Book(models.Model):
    title = models.CharField(
        "Title",
        max_length=100,
        blank=False,
        null=False
    )

    description = models.TextField(
        "About the book",
        max_length=500,
        blank=True,
        null=True
    )

    cover_photo = models.ImageField(
        "Cover",
        upload_to='media/'
    )

    author_id = models.ManyToManyField(Author)

    genre_id = models.ManyToManyField(Genre)

    series = models.ForeignKey(
        Series,
        default=1,
        on_delete=models.PROTECT
    )

    publisher = models.ForeignKey(
        Publisher,
        default=1,
        on_delete=models.PROTECT
    )

    price = models.DecimalField(
        "Price (BYN)",
        default=0.0,
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False
    )


    publishing_date = models.DateField(
        "Date published",
        default=date.today,
        blank=False,
        null=False
    )

    pages_num = models.PositiveIntegerField(
        "Number of pages",
        default=0,
        blank=False,
        null=False
    )

    binding = models.CharField(
        "Binding",
        default="",
        max_length=50,
        blank=False,
        null=False
    )
    
    format = models.ForeignKey(
        Format,
        default=1,
        on_delete=models.PROTECT
    )

    ISBN = models.PositiveIntegerField(
        "ISBN",
        default=0,
        blank=False,
        null=False
    )

    weight = models.PositiveIntegerField(
        "Weight (g)",
        default=0,
        blank=False,
        null=False
    )

    age_res = models.ForeignKey(
        Age_res,
        default=1,
        on_delete=models.PROTECT
    )

    stock_number = models.PositiveIntegerField(
        "Left in stock",
        default=0,
        blank=False,
        null=False
    )

    ACTIVE_OPTIONS = ((True, 'Yes'), (False, 'No'))

    is_active = models.BooleanField(
        "Is active?",
        choices=ACTIVE_OPTIONS,
        default=True,
        blank=False,
        null=False
    )

    rating = models.ForeignKey(
        Rating,
        default=1,
        on_delete=models.PROTECT
    )


    entry_date = models.DateTimeField(
        "Date of entry",
        auto_now_add=True,
        null=True,
        blank=True
    )

    update_date = models.DateTimeField(
        "Date of update",
        auto_now=True,
        null=True,
        blank=True
    )



    def __str__(self):
        return self.title

bookstore/src/book/forms.py
from django import forms
from . import models



class CreateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ('__all__')

class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ('__all__')

bookstore/src/book/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.db.models import Q
from django.urls import reverse_lazy
import requests

from refference_db.models import *
from .models import Book
from .forms import *




class BookListView(ListView):
    """displays a list of all Book objects"""

    template_name = "book/main_page.html"
    model = Book
    paginate_by = 12

class BookView(DetailView):
    """displays a single Book objects"""

    newdeals = Book.objects.all().order_by('-pk')[:4]
    extra_context = {'newdeals':newdeals}
    model = Book
    template_name = "book/book.html"

class CreateBookView(CreateView):
    """creates a single book object"""

    model = Book
    fields = '__all__'
    template_name = 'book/create_book.html'
    success_url = '/'

class UpdateBookView(UpdateView):
    """updates a single book object"""

    model = Book
    fields = '__all__'
    template_name = 'book/update_book.html'
    success_url = '/'

class DeleteBookView(DeleteView):
    model = Book
    template_name = 'book/delete_view.html'
    success_url = '/'


class MainPageView(ListView):
    """displays a main page"""

    template_name = "book/main_page.html"
    model = Book
    queryset = Book.objects.all().order_by('-pk')[:10]

    def get_current_rate(self):
        result = requests.get('https://www.nbrb.by/api/exrates/rates/145')
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["fresh_arrivals"] = Book.objects.order_by('-pk')[:6]
        context["most_popular"] = Book.objects.order_by('-rating')[:6]
        context['user'] = self.request.user
        context['genres'] = Genre.objects.all()
        try:
            page = self.get_current_rate()
            rate = page.json()['Cur_OfficialRate']
            context['rate'] = rate
            
        except requests.exceptions.ConnectionError:
            requests.status_code = "Connection refused"
        return context

class BookSearch(ListView):
    model = Book
    template_name = 'book/book_catalog.html'
    paginate_by = 12
    
    def get_template_names(self):
        search = self.request.GET.get('search')
        books = Book.objects.filter(Q(title__icontains=search))
        if not books.exists():
            template_name = "catalog/empty.html"
            return ["catalog/empty.html"]
        else:
            return [self.template_name]


    def get_queryset(self):
        search = self.request.GET.get('search')
        books = Book.objects.filter(Q(title__icontains=search))
        return books
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_info = str(self.request.GET.get('search'))
        context["search"] = search_info
        return context
    

bookstore/src/book/templates/book/book_catalog.html
<!DOCTYPE html>
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Genre: {{ genre.genre }}
{% endblock title %}
{% block body %}


<h1>{{ genre.genre }}</h1>

   

<section>

        <h3 class="text-center pt-5 mb-0">Search results for: {{ search }} </h3>

        <!-- Grid row -->
        <div class="row mt-5 mb-4">
        
        {% for book  in object_list %}
          <!-- Grid column -->
          <div class="col-md-6 col-lg-3 mb-4">

            <!-- Card -->
            <div class="">

              <div  class="view zoom z-depth-2 rounded">
                <img class="shadow rounded mr-3" width="180" height="200" src="{{ book.cover_photo.url }}" alt="Sample">
                <a href="{% url 'book-view' book.pk %}">
                  <div class="mask"></div>
                </a>
              </div>

              <div class="text-center pt-4">

                <h5>{{ book.title }}</h5>
                <h6 class="mb-3">{{ book.price }} BYN </h6>
                <a href="{% url 'orders:cart' %}?book={{ book.pk }}" class="btn btn-primary btn-sm mr-1"><i class="fas fa-shopping-cart pr-2"></i>Add to cart</a>
                <a href="{% url 'book-view' book.pk %}" class="btn btn-danger btn-sm px-3 material-tooltip-main" data-toggle="tooltip"
                  data-placement="top"><i class="far fa-eye"></i></a>

              </div>

            </div>
            <!-- Card -->

          </div>
          {% endfor %}
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </section>


{% endblock body %}

bookstore/src/book/templates/book/create_book.html
{% extends 'customer_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Create Book
{% endblock title %}
{% block body %}

      <h1>Create Book</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Submit</button>

{% endblock body %}
    

bookstore/src/book/templates/book/main_page.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Main</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static "carousel.css" %}" rel="stylesheet">
  </head>
  <body>
    <header>
  <nav class="navbar fixed-top navbar-light navbar-expand-md bg-light justify-content-center">
      <a href="/" class="navbar-brand mr-0">City-Reads</a>
      <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
          <ul class="navbar-nav mx-auto text-center">
              <li class="nav-item">
                  <a class="nav-link" href="/catalog/">Catalog</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shipping' %}">Shipping and Payments</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'return' %}">Returns</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
              </li>
              <li class="nav-item">
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
              <input name="search" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
              </li>
              <li class="nav-item">
               {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'profile:profile-view' %}"><i class="far fa-user"></i></a>
              </li>
              {% else %}
                <a class="nav-link" href="{% url 'profile:login' %}">Sign in</a>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href=""><i class="far fa-heart"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/cart/"><i class="fas fa-shopping-bag"></i></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="#"></a></li> 
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>   
            {% else %}
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:signup' %}"> <i class="fas fa-sign-in-alt"></i> Signup</a></li>   
            {% endif %} 
              <li class="nav-item">
              <a class="nav-link" href="https://www.nbrb.by/statistics/rates/ratesdaily.asp"> BYN/USD: {{ rate }}</a>
              </li>
              {% if user.is_staff or user.is_superuser %}
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'manager:book-list' %}">
                <button class="btn btn-secondary">Administration</button>
              </a>
              </li>
              {% endif %}
            </ul>
      </div>
  </nav>
</header>

<main role="main">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#5D5BB0"/></svg>
        <img src="{% static "main.svg" %}" class="d-block w-100" alt="...">
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Hot updats!</h1>
            <p>Check our freshest deals!</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'catalog' %}" role="button">Buy now</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#5D5BB0"/></svg>
        <img src="{% static "main.svg" %}" class="d-block w-100" alt="...">
        <div class="container">
          <div class="carousel-caption">
            <h1>Top rated</h1>
            <p>Our most rated books, check them now!</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'catalog' %}" role="button">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#5D5BB0"/></svg>
        <img src="{% static "main.svg" %}" class="d-block w-100" alt="...">
        <div class="container">
          <div class="carousel-caption text-right">
            <h1>Look into the catalog!</h1>
            <p>Only the best books on the planet.</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'catalog' %}" role="button">Browse catalog</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

 <div class="card-deck">
      {% for book  in object_list %}
      <div class="card">
        <a class="linky" href="{% url 'book-view' book.pk %}">
          <img src={{ book.cover_photo.url }} class="card-img-top">
        </a>
          <div class="card-body">
            <h5 class="card-title">{{book.title}}</h5>
            {% for auth in book.author_id.all %}
            <p class="card-text">{{ auth }}</p>
            {% endfor %}
          </div>
          <div class="card-footer">
            <small class="text-muted">{{ book.price }} BYN </small>
          </div>
      </div>
    {% endfor %}
    </div>

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
         <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <a href="" class="navbar-brand mr-0">City Reads</a>
        <small class="d-block mb-3 text-muted">Minsk, Pervomayskaya str. 24</small>
        <small class="d-block mb-3 text-muted">chitaygorod@gmail.com</small>
        <small class="d-block mb-3 text-muted">8(800)854 856 888</small>
      </div>
      <div class="col-6 col-md">
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="{% url 'about' %}">About us</a></li>
          <li><a class="text-muted" href="/catalog/">Catalog</a></li>
          <li><a class="text-muted" href="{% url 'shipping' %}">Shipping and Payments</a></li>
          <li><a class="text-muted" href="{% url 'return' %}">Returns</a></li>
          <li><a class="text-muted" href="{% url 'contacts' %}">Contacts</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Payment methods</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted"><i class="fab fa-cc-visa"> Visa</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-mastercard"> Mastercard</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-paypal"> PayPal</i></a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Our socials</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-vk"></i> Vkontakte</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
        </ul>
      </div>
    </div>
  </footer>
</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>