bookstore/src/authentication/urls.py
from django.urls import path
from .views import *

app_name = 'profile'
urlpatterns = [
    path('signin/', AuthenticationView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', AuthLogoutView.as_view(), name='logout'),
    path('password_change/', AuthPasswordChangeView.as_view(), name='password-change'),
    path('password_change_success/', AuthPasswordUpdDoneView.as_view(), name='password-updt-success'),
    path('auth/', ProfileView.as_view(), name='profile-view'),
    path('<int:pk>/update/', UpdateProfileView.as_view(), name='profile-update'),
]

bookstore/src/manager_admin/urls.py
from django.urls import path
from .views import *

app_name = 'manager'
urlpatterns = [
    path('order/list/', ManagerOrderList.as_view(), name='order-list'),
    path('order/update/<int:pk>/', ManagerOrderUpdate.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', ManagerOrderDelete.as_view(), name='order-delete'),

    path('author/list/', AuthorList.as_view(), name='author-list'),
    path('author/create/', AuthorCreate.as_view(), name='author-create'),
    path('author/view/<int:pk>/', AuthorView.as_view(), name='author-view'),
    path('author/delete/<int:pk>/', AuthorDelete.as_view(), name='author-delete'),
    path('author/update/<int:pk>/', AuthorUpdate.as_view(), name='author-update'),


    path('series/list/', SeriesList.as_view(), name='series-list'),
    path('series/create/', SeriesCreate.as_view(), name='series-create'),
    path('series/view/<int:pk>/', SeriesView.as_view(), name='series-view'),
    path('series/update/<int:pk>/', SeriesUpdate.as_view(), name='series-update'),
    path('series/delete/<int:pk>/', SeriesDelete.as_view(), name='series-delete'),


    path('genre/list/', GenreList.as_view(), name='genre-list'),
    path('genre/create/', GenreCreate.as_view(), name='genre-create'),
    path('genre/view/<int:pk>/', GenreView.as_view(), name='genre-view'),
    path('genre/update/<int:pk>/', GenreUpdate.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>/', GenreDelete.as_view(), name='genre-delete'),


    path('publisher/list/', PublisherList.as_view(), name='publisher-list'),
    path('publisher/create/', PublisherCreate.as_view(), name='publisher-create'),
    path('publisher/view/<int:pk>/', PublisherView.as_view(), name='publisher-view'),
    path('publisher/update/<int:pk>/', PublisherUpdate.as_view(), name='publisher-update'),
    path('publisher/delete/<int:pk>/', PublisherDelete.as_view(), name='publisher-delete'),

    
    path('format/', FormatListView.as_view(), name = 'format-list-view'),
    path('format/<int:pk>/', FormatView.as_view(), name = 'format-view'),
    path('format/create/', CreateFormatView.as_view(), name = 'format-create'),
    path('format/update/<int:pk>/', UpdateFormatView.as_view(), name = 'format-update'),
    path('format/delete/<int:pk>/', DeleteFormatView.as_view(), name = 'format-delete'),
    
    path('age/', Age_resListView.as_view(), name = 'ageres-list-view'),
    path('age/<int:pk>/', Age_resView.as_view(), name = 'ageres-view'),
    path('age/create/', CreateAge_resView.as_view(), name = 'ageres-create'),
    path('age/update/<int:pk>/', UpdateAge_resView.as_view(), name = 'ageres-update'),
    path('age/delete/<int:pk>/', DeleteAge_resView.as_view(), name = 'ageres-delete'),
    
    path('rating/', RatingListView.as_view(), name = 'rating-list-view'),
    path('rating/<int:pk>/', RatingView.as_view(), name = 'rating-view'),
    path('rating/create/', CreateRatingView.as_view(), name = 'rating-create'),
    path('rating/update/<int:pk>/', UpdateRatingView.as_view(), name = 'rating-update'),
    path('rating/delete/<int:pk>/', DeleteRatingView.as_view(), name = 'rating-delete'),


    path('book/list/', ManagerBookList.as_view(), name='book-list'),
    path('book/create/', ManagerBookCreate.as_view(), name='book-create'),
    path('book/delete/<int:pk>/', ManagerBookDelete.as_view(), name='book-delete'),
    path('book/update/<int:pk>/', ManagerBookUpdate.as_view(), name='book-update'),
    path('book/view/<int:pk>/', ManagerBookView.as_view(), name='book-view'),


    path('customer/list/', CustomersList.as_view(), name='customer-list'),
    path('customer/update/<int:pk>/', CustomerUpdate.as_view(), name='customer-update'),
    path('customer/view/<int:pk>/', CustomerView.as_view(), name='customer-view')

    
]

bookstore/src/orders/urls.py
from django.urls import path
from django.views.generic.base import View

from book.views import *
from refference_db.views import *
from .views import *

app_name = 'orders'
urlpatterns = [
    path('', CartView.as_view(), name = 'cart'),
    path('update-cart', CartUpdateView.as_view(), name = 'update'),
    path('delete-book-in-cart/<int:pk>', DeleteBookInCart.as_view(), name = 'book-in-cart-del'),
    path('order/', CreateOrderView.as_view(), name='create-order'),
    path('history/', HistoryDetailView.as_view(), name='history')

]

bookstore/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from catalog.views import *
from book.views import *
from refference_db.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('authentication.urls', namespace='profile')),

    path('book/search/', BookSearch.as_view(), name='search'),
    path('book/<int:pk>/', BookView.as_view(), name = 'book-view'),
    path('book/create/', CreateBookView.as_view(), name = 'book-create'),
    path('book/update/<int:pk>/', UpdateBookView.as_view(), name = 'book-update'),
    path('book/delete/<int:pk>/', DeleteBookView.as_view(), name = 'book-delete'),

    path('genre/', GenreListView.as_view(), name = 'genre-list-view'),
    path('genre/<int:pk>/', GenreView.as_view(), name = 'genre-view'),
    path('genre/create/', CreateGenreView.as_view(), name = 'genre-create'),
    path('genre/update/<int:pk>/', UpdateGenreView.as_view(), name = 'genre-update'),
    path('genre/delete/<int:pk>/', DeleteGenreView.as_view(), name = 'genre-delete'),
    
    path('author/', AuthorListView.as_view(), name = 'author-list-view'),
    path('author/<int:pk>/', AuthorView.as_view(), name = 'author-view'),
    path('author/create/', CreateAuthorView.as_view(), name = 'author-create'),
    path('author/update/<int:pk>/', UpdateAuthorView.as_view(), name = 'author-update'),
    path('author/delete/<int:pk>/', DeleteAuthorView.as_view(), name = 'author-delete'),
    
    path('series/', SeriesListView.as_view(), name = 'series-list-view'),
    path('series/<int:pk>/', SeriesView.as_view(), name = 'series-view'),
    path('series/create/', CreateSeriesView.as_view(), name = 'series-create'),
    path('series/update/<int:pk>/', UpdateSeriesView.as_view(), name = 'series-update'),
    path('series/delete/<int:pk>/', DeleteSeriesView.as_view(), name = 'series-delete'),
    
    path('publisher/', PublisherListView.as_view(), name = 'publisher-list-view'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name = 'publisher-view'),
    path('publisher/create/', CreatePublisherView.as_view(), name = 'publisher-create'),
    path('publisher/update/<int:pk>/', UpdatePublisherView.as_view(), name = 'publisher-update'),
    path('publisher/delete/<int:pk>/', DeletePublisherView.as_view(), name = 'publisher-delete'),
    
    path('format/', FormatListView.as_view(), name = 'format-list-view'),
    path('format/<int:pk>/', FormatView.as_view(), name = 'format-view'),
    path('format/create/', CreateFormatView.as_view(), name = 'format-create'),
    path('format/update/<int:pk>/', UpdateFormatView.as_view(), name = 'format-update'),
    path('format/delete/<int:pk>/', DeleteFormatView.as_view(), name = 'format-delete'),
    
    path('age/', Age_resListView.as_view(), name = 'ageres-list-view'),
    path('age/<int:pk>/', Age_resView.as_view(), name = 'ageres-view'),
    path('age/create/', CreateAge_resView.as_view(), name = 'ageres-create'),
    path('age/update/<int:pk>/', UpdateAge_resView.as_view(), name = 'ageres-update'),
    path('age/delete/<int:pk>/', DeleteAge_resView.as_view(), name = 'ageres-delete'),
    
    path('rating/', RatingListView.as_view(), name = 'rating-list-view'),
    path('rating/<int:pk>/', RatingView.as_view(), name = 'rating-view'),
    path('rating/create/', CreateRatingView.as_view(), name = 'rating-create'),
    path('rating/update/<int:pk>/', UpdateRatingView.as_view(), name = 'rating-update'),
    path('rating/delete/<int:pk>/', DeleteRatingView.as_view(), name = 'rating-delete'),

    path('error/', ErrorView.as_view(), name = 'error'),
    path('empty/', EmptyView.as_view(), name = 'empty'),
    path('return/', ReturnView.as_view(), name = 'return'),
    path('about/', AboutView.as_view(), name = 'about'),
    path('shipping/', ShippingView.as_view(), name = 'shipping'),
    path('contacts/', ContactsView.as_view(), name = 'contacts'),
    path('cart/', include('orders.urls', namespace = 'orders')),
    path('catalog/', include('catalog.urls')),
    
    path('test/', BookListView.as_view(), name = 'main-manager'),
    path('manager/', include('manager_admin.urls', namespace = 'manager')),
    path('', MainPageView.as_view(), name = 'main')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/src/templates/admins_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block head %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
    <!-- Custom styles for this template -->
    <link href="{% static "starter-template.css" %}" rel="stylesheet">
    {% endblock head %}
    <title>{% block title %}Default title{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-light navbar-expand-md bg-light justify-content-center">
      <a href="/" class="navbar-brand mr-0">City-Reads</a>
      <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
          <ul class="navbar-nav mx-auto text-center">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'catalog' %}">Catalog</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'manager:order-list' %}">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:customer-list' %}">Customers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:book-list' %}">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:genre-list' %}">Genre</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:genre-list' %}">Genre</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:series-list' %}">Series</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:author-list' %}">Author</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:publisher-list' %}">Publisher</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:format-list-view' %}">Format</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:ageres-list-view' %}">Age</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:rating-list-view' %}">Rating</a>
              </li>
              <li class="nav-item">
               {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'profile:profile-view' %}"><i class="far fa-user"></i></a>
              </li>
              {% else %}
                <a class="nav-link" href="{% url 'profile:login' %}">Sign in</a>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href=""><i class="far fa-heart"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/cart/"><i class="fas fa-shopping-bag"></i></a>
              </li>
              <li class="nav-item">
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
              <input name="search" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="#"></a></li> 
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>   
            {% else %}
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:signup' %}"> <i class="fas fa-sign-in-alt"></i> Signup</a></li>   
            {% endif %} 
            </ul>
      </div>
  </nav>
  
    
      <div class="starter-template">
        {% block body %}
        {% endblock body %}
      </div>
    
     <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <a href="" class="navbar-brand mr-0">City Reads</a>
        <small class="d-block mb-3 text-muted">Minsk, Pervomayskaya str. 24</small>
        <small class="d-block mb-3 text-muted">chitaygorod@gmail.com</small>
        <small class="d-block mb-3 text-muted">8(800)854 856 888</small>
      </div>
      <div class="col-6 col-md">
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="{% url 'about' %}">About us</a></li>
          <li><a class="text-muted" href="{% url 'catalog' %}">Catalog</a></li>
          <li><a class="text-muted" href="{% url 'shipping' %}">Shipping and Payments</a></li>
          <li><a class="text-muted" href="{% url 'return' %}">Returns</a></li>
          <li><a class="text-muted" href="{% url 'contacts' %}">Contacts</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Payment methods</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted"><i class="fab fa-cc-visa"> Visa</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-mastercard"> Mastercard</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-paypal"> PayPal</i></a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Our socials</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-vk"></i> Vkontakte</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
        </ul>
      </div>
    </div>
  </footer>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
   
  </body>
</html>

bookstore/src/templates/customer_base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block head %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
    <!-- Custom styles for this template -->
    <link href="{% static "starter-template.css" %}" rel="stylesheet">
    {% endblock head %}
    <title>{% block title %}Default title{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-light navbar-expand-md bg-light justify-content-center">
      <a href="/" class="navbar-brand mr-0">City-Reads</a>
      <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
          <ul class="navbar-nav mx-auto text-center">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'catalog' %}">Catalog</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shipping' %}">Shipping and Payments</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'return' %}">Returns</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
              </li>
              <li class="nav-item">
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
              <input name="search" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
              </li>
              <li class="nav-item">
               {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'profile:profile-view' %}"><i class="far fa-user"></i></a>
              </li>
              {% else %}
                <a class="nav-link" href="{% url 'profile:login' %}">Sign in</a>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href=""><i class="far fa-heart"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/cart/"><i class="fas fa-shopping-bag"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'orders:history' %}"><i class="fas fa-history"></i></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="#"></a></li> 
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>   
            {% else %}
              <li class="nav-item"> <a class="nav-link" href="{% url 'profile:signup' %}"> <i class="fas fa-sign-in-alt"></i> Signup</a></li>   
            {% endif %} 
              <li class="nav-item">
              <a class="nav-link" href="https://www.nbrb.by/statistics/rates/ratesdaily.asp"> BYN/USD RATE: {{ rate }}</a>
              </li>
              {% if user.is_staff or user.is_superuser %}
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'manager:book-list' %}">
                <button class="btn btn-secondary">Administration</button>
              </a>
              </li>
              {% endif %}
            </ul>
      </div>
  </nav>
  
    
      <div class="starter-template">
        {% block body %}
        {% endblock body %}
      </div>
    
     <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <a href="" class="navbar-brand mr-0">City Reads</a>
        <small class="d-block mb-3 text-muted">Minsk, Pervomayskaya str. 24</small>
        <small class="d-block mb-3 text-muted">chitaygorod@gmail.com</small>
        <small class="d-block mb-3 text-muted">8(800)854 856 888</small>
      </div>
      <div class="col-6 col-md">
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="{% url 'about' %}">About us</a></li>
          <li><a class="text-muted" href="{% url 'catalog' %}">Catalog</a></li>
          <li><a class="text-muted" href="{% url 'shipping' %}">Shipping and Payments</a></li>
          <li><a class="text-muted" href="{% url 'return' %}">Returns</a></li>
          <li><a class="text-muted" href="{% url 'contacts' %}">Contacts</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Payment methods</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted"><i class="fab fa-cc-visa"> Visa</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-mastercard"> Mastercard</i></a></li>
          <li><a class="text-muted"><i class="fab fa-cc-paypal"> PayPal</i></a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Our socials</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-vk"></i> Vkontakte</a></li>
          <li><a class="text-muted" href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
        </ul>
      </div>
    </div>
  </footer>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
   
  </body>
</html>